name: generate snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia
  workflow_dispatch:

permissions:
  contents: write # 🔥 ESSENCIAL pra conseguir dar push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: RhoanBarioni
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}